apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-sa # Ensure this service account exists in the jenkins namespace
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-role # This should match the Role defined above
  apiGroup: rbac.authorization.k8s.io
