apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-sa
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-role
  namespace: devops-tools
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-role-binding
  namespace: jenkins-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-role
subjects:
- kind: ServiceAccount
  name: admin-sa
  namespace: jenkins-ns

